### PR TITLE
Build on MSYS2 MINGW64

### PR DESCRIPTION
**Pull request by iahung**
- Remove MSVC specifics
- Replace symbolic links with real files
- Create makefile.msys2 for MSYS2 MINGW64

### CODE REVIEW

**Comment by fegennari** [comment]
Okay, a few questions. Why did you replace the symlinks with a single include file? Was there a problem with the way this was done? I'll need to determine if Visual Studio can still find the files when done this way. It does seem cleaner though.

Most of the changes made to 3DWorld.cpp look like whitespace changes. Maybe changes to line ends? I'm curious what editor you used to make the changes. I think the only important changes are a few lines at the top of the file.

Thanks. I'll look at this in more detail tonight after work.

**Comment by iahung** [comment]
> Okay, a few questions. Why did you replace the symlinks with a single include file? Was there a problem with the way this was done? I'll need to determine if Visual Studio can still find the files when done this way. It does seem cleaner though.
> 
> Most of the changes made to 3DWorld.cpp look like whitespace changes. Maybe changes to line ends? I'm curious what editor you used to make the changes. I think the only important changes are a few lines at the top of the file.
> 
> Thanks. I'll look at this in more detail tonight after work.

Symbolic links are causing troubles on MSYS2 MINGW64 as it seems `git` created them as normal files. You could use a text editor to open them, you will see they are text files with the content exactly like what you see when viewing them on Github:

https://github.com/fegennari/3DWorld/blob/004b1599ff9448045380f4f9b2d6fcb65b218f2b/src/simplifier.cpp

https://github.com/fegennari/3DWorld/blob/004b1599ff9448045380f4f9b2d6fcb65b218f2b/src/targa.cpp

https://github.com/fegennari/3DWorld/blob/004b1599ff9448045380f4f9b2d6fcb65b218f2b/src/texture_tile_blend.cpp

I edited the files via Github's web interface as the changes are too trivial to make a `git push`.

**Comment by fegennari** [comment]
Okay, I merged in your changes. I tested on both Windows with MS Visual Studio and linux with gcc and everything appears to be working. Thanks for the fixes! Do you have it working in MinGW now?

**Comment by iahung** [comment]
> Okay, I merged in your changes. I tested on both Windows with MS Visual Studio and linux with gcc and everything appears to be working. Thanks for the fixes! Do you have it working in MinGW now?

The build completed without errors but I didn't test the generated binaries to see if they are working fine or not.

**Comment by fegennari** [comment]
Okay, let me know if you have any problems or need anything else.

**Pull request merged**
